name: Tests on macOS

on:
  push:
  pull_request:

jobs:
  test:
    name: Test job
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Create CMake build tree"
        run: |
          mkdir -p build && cd build && cmake -DENABLE_ASAN=True ..

      - name: "Run tests"
        run: |
          cd build && make tests-unit && ./tests/tests-unit
